import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Provider from "@/components/Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Prompt } from "next/font/google";
import { Suspense } from "react";

const prompt = Prompt({
  weight: "400",
  subsets: ["latin", "thai"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Find Work - Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${prompt.className} antialiased`}>
          <Provider>
            <Navbar />
            <main className="container">{children}</main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
